#!/bin/bash
# Script to run the python lights controller
LOGF="/home/pi/Desktop/STC-Lights/RPi-controller/lights.log"
while true; do
    if [ -f "$LOGF" ]; then # move the old log file out of the way and date-stamp it
        mv "$LOGF" "$LOGF-$(date +%F-%T)"
    fi
	sudo python3 /home/pi/Desktop/STC-Lights/RPi-controller/lights-main.py
	wget -O - http://lymingtonchurch.org/lights/s-report-error.php?"lights-main completed with error $?"
	sleep 5
done
